### ISSUE TITLE
Module gdal not found in conda environment

### ISSUE THREAD

**Issue by IvanPalm** [boku-iwa/Floodplain-Evaluation-Matrix-Tool#9]
I have `qgis 3.18.3` installed in a conda environment via the `conda-forge` [channel](https://anaconda.org/conda-forge/qgis). In the same environment I installed  `gdal 3.3.1` via the same [channel](https://anaconda.org/conda-forge/gdal).

When trying to installed the plugin from zip, I got a `ModuleNotFoundError` pointing at `gdal`.

![Screenshot from 2021-11-25 13-18-07](https://user-images.githubusercontent.com/46936982/143442594-e731960a-c628-4744-b0a3-9db7dabbdb5d.png)

It is known that `import gdal` was [removed](https://github.com/OSGeo/gdal/blob/v3.2.1/gdal/NEWS) in `gdal 3.2` and replaced with `from osgeo import gdal`, with direct [consequences](https://gis.stackexchange.com/questions/393212/import-gdal-vs-import-osgeo-gdal) on pre-existing codes.

I checked your codes are realized that this was the reason for the error thrown while installing the plugin, namely on line 5 of `test_plugin.py`. I've forked and edited the import with a try except statement.

This enabled me to install the plugin from zip. Please let me know whether you want me to send a pull request with the minor changes I made to your code.

**Comment by sncrycsn** [comment]
Hi Ivan,

Thank you for your message. The proposed method to solve this issue seemed quite fine for me. I will immediately issue the changes.

Best regards,
Sencer
